### ISSUE TITLE
about the code release

### ISSUE THREAD

**Issue by CodeWZT** [AronCao49/MoPA#1] opened 2024-07-16 06:23 UTC
Thank you for your excellent work. When will you release the complete training and testing code?

**Comment by AronCao49** [comment] 2024-07-16 06:34
Hi, thanks for your interest in this work. We have spent some time refactoring our code and double-checking the reproducibility, which takes longer than we expected due to the limited computational resources we have...

But the good news is that all testing works are nearly completed. We are planning to release the full code along with the checkpoints within these two weeks. Please stay tuned and we will keep you updated.

**Comment by CodeWZT** [comment] 2024-07-16 06:36
Thank you very much for your prompt response. I look forward to the full release of your code. Your work is highly meaningful.

**Comment by AronCao49** [comment] 2024-08-02 05:34
@CodeWZT Full code is now available now and I will then close this issue :)

**Closed as completed by AronCao49** 2024-08-02 05:34 UTC
